services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tickets
    volumes:
      - pg-data:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    volumes:
      - .:/app:cached
    ports:
      - 8000:8000
    env_file:
      - .env
    build: .
    tty: true
    command: >
      sh -c "
      mkdir -p /app/static &&
      python /app/manage.py makemigrations --noinput &&
      python /app/manage.py migrate &&
      python /app/manage.py makemigrations app --noinput &&
      python /app/manage.py migrate app &&
      python /app/manage.py collectstatic --no-input --clear &&
      python /app/manage.py loaddata /app/app/fixtures/local_data.json &&
      python /app/manage.py runserver 0.0.0.0:8000
      "

volumes:
  pg-data:
