# Generated by Django 3.2.25 on 2024-04-08 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('closed', 'Closed'), ('pending', 'Pending')], default='open', max_length=255)),
                ('priority', models.IntegerField(choices=[(1, 'P1'), (2, 'P2'), (3, 'P3')], default=2)),
                ('resolution', models.CharField(blank=True, choices=[('hardware', 'Hardware'), ('customer', 'Customer'), ('thirdparty', 'Third party'), ('operations', 'Operations'), ('change', 'Change'), ('merged', 'Merged')], max_length=255, null=True)),
                ('response_eta', models.DateTimeField(blank=True, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby', to=settings.AUTH_USER_MODEL)),
                ('infrastructure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.infrastructure')),
            ],
        ),
    ]
